### ISSUE TITLE
Changed Advancement Received Message

### ISSUE THREAD

**Issue by NillerMedDild** [someaddons/ClickableAdvancements#1]
**Describe the bug**
Only the name of advancements achieved are shown, not the standard "Advancement get" part.

**To Reproduce**
1. Start a world
2. Earn any advancement
3. See bug

**Expected behavior**
For the message to appear the same as normally

** Mod version **
clickadv-1.3

** Logs **
Latest/Crash log

**Comment by someaddons** [comment]
Those with just the names are advancements which are normally not shown, and potentially have no other text. Advancements in vanilla decide between broadcast to all and not showing up in the chat at all. By default clickable advancements puts them all into the chat so you can find where they are, though you can toggle the config to not display those instead.

**Comment by NillerMedDild** [comment]
Oh that's what the config does 😅 thanks!

**Comment by someaddons** [comment]
ye its a bit weird that its either broadcast to all players or no display at all^^
