### ISSUE TITLE
[1.18.2 Bug]: First part of text not appearing in chat

### ISSUE THREAD

**Issue by vizthex123** [someaddons/ClickableAdvancements#10]
### Describe the bug you're experiencing

Normally, the game will print "<username> has made the advancement [Name]!", but this mod keeps removing that text for modded advancements, as seen below with this one from Create:
![image](https://user-images.githubusercontent.com/31721920/178416425-5c621e07-aa88-4036-a2e7-883450f79ff3.png)

In addition, I'm on 1.18.2 - but this form doesn't have an option for that.

### Reproducability
Gain an advancement with the mod enabled. Changing the config doesn't seem to affect this bug.

### Mod up to date
- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version
1.18.1

### Modloader version
Forge

### Logs
https://gist.github.com/vizthex123/e81d3ce9914c6a26d3f4150108a3d85b

**Comment by someaddons** [comment]
its a feature, which displays advancements in chat which normally are not shown. If you don't want those turn off the config on serverside
```
#By default vanilla only displays advancements in chat which get broadcasted to all online players,this setting turns on showing all advancements achieved in chat instead. 
That way you can findthe advancements you got easier/see better which you get. 
Some of these may have no actual text though because the advancement itself doesnt have any, e.g. Categories are advancements too. default = true
showAllInLocalChat = true
```
