### ISSUE TITLE
[Bug]: 1.19 Crash on open new world with Majrusz Progressive Difficulty

### ISSUE THREAD

**Issue by Baggytrousers27** [someaddons/ClickableAdvancements#11]
### Describe the bug you're experiencing

Forge 1.19 41.0.106
clickadv-1.19-2.5
majrusz-library-1.19-2.11.0
majruszs-difficulty-1.19-1.5.5

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.minecraftforge.event.entity.player.AdvancementEvent.getPlayer()'
Exit Code: -1

### Reproducability

Try to load up a new world with the above mods and crash to launcher with above message.
Also 1.19 is missing from the minecraft version select, below.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/Baggytrousers27/dc0b50b03ce80e74f02a0861578f5deb

**Comment by Baggytrousers27** [comment]
If clickadv is added after world is created then everything runs as normal.

**Comment by ProsperCraft** [comment]
Same here on TownCraft for 1.19
https://gist.githubusercontent.com/ProsperCraft/8a2f4b27a75b1aa9a0264c9944d9dc3d/raw/ede1cd218cd3d4f8fed7dd07ed737c4e1d0b2b5b/gistfile1.txt

**Comment by someaddons** [comment]
fixed, just the forge refactor breaking everything

**Comment by Baggytrousers27** [comment]
Good news, Forge 1.19 finally has a stable release. Fingies crossed it won't set my dog on fire.
