### ISSUE TITLE
Consider adding mod to modrinth.

### ISSUE THREAD

**Issue by SzczurekYT** [someaddons/ClickableAdvancements#12]
Hello
Some time ago a new site hosting mods showed up. It's called [Modrinth](https://modrinth.com) and has a really nice ui, and I would say it's overall better then curseforge, the ui is faster, looks nicer, and has good working filters. Could you please consider adding you mod there?
Thanks

**Comment by someaddons** [comment]
sure, once they have a proper reward system

**Comment by SzczurekYT** [comment]
> sure, once they have a proper reward system

They added it around a month ago, you can read more about this on their blog [post](https://blog.modrinth.com/creator-monetization-beta/).

**Comment by aaronliu0130** [comment]
@someaddons is there an update on this?
