### ISSUE TITLE
[Bug]: Config doesn't generate on 1.19.2

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [someaddons/ClickableAdvancements#14]
### Describe the bug you're experiencing

Config file doesn't generate at all.

### Reproducability

Simply install the mod and run the game, then check your config folder.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Fabric

### Logs

https://gist.github.com/Footage2-Amply-Pounce/e5600dbe547cfe93939610fe8d3339d9

**Comment by someaddons** [comment]
fixed
