### ISSUE TITLE
[Bug]: spamming recipes other mods

### ISSUE THREAD

**Issue by jarocajavi** [someaddons/ClickableAdvancements#15]
### Describe the bug you're experiencing

I made a big modpack, and i found an uncompatibility in clickableAdvancements with:
- Better End
- Better Nether
- Bclib
- Eden Ring
Game Version: 1.19.2
Fabric Version launcher: 0.14.9
Fabric Version Api: 0.60.0

Explanation: when you get any item than unlock a recipe the chat shows the green message of the picture
https://i.imgur.com/6PYjKQS.png

I have check it just fabric + bclib + clickadv and can be replicate the error.

Thanks for your time :)

### Reproducability

Tested with server+client mode
Mods server & client: fabric_api + bclib + clickadv

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/jarocajavi/d6ea701d0144b2c298ae0699897a7c34

**Comment by jarocajavi** [comment]
https://github.com/Siphalor/nbt-crafting/issues/118

**Comment by spoorn** [comment]
Having the same problem, I don't have NBT Crafting installed though so it's not because of that

**Comment by someaddons** [comment]
its a feature, which displays advancements in chat which normally are not shown. If you don't want those turn off the config on serverside
```
#By default vanilla only displays advancements in chat which get broadcasted to all online players,this setting turns on showing all advancements achieved in chat instead. 
That way you can findthe advancements you got easier/see better which you get. 
Some of these may have no actual text though because the advancement itself doesnt have any, e.g. Categories are advancements too. default = true
showAllInLocalChat = true
```
