### ISSUE TITLE
[Bug]: 3 mod cross-conflict in 1.19.2

### ISSUE THREAD

**Issue by Zygus42** [someaddons/ClickableAdvancements#16]
### Describe the bug you're experiencing

I will start by saying that this bug only happens when 2 particular mods and a datapack are together, and I have no clue which one it is that's the root cause.

Whenever you right click with a torch (or anything else), you get the following messages in chat:
![2022-09-22_14 22 08](https://user-images.githubusercontent.com/20757445/191740078-f28e02c3-33bc-4a48-a18f-0a24ccec1e92.png)

### Reproducability

This only happens when you have the mods:
   clickadv-1.19.2-2.9
   Shrines-1.19.2-5.0.0-alpha4
and the datapack:
  new-in-town-by-kanokarob-v2-11-5
together.

Using forge-1.19.2-43.1.25-installer.

Any two of these and there's no problem.  You don't even want to know how long it took me to work this out !
Debug log:
[debug.log](https://github.com/someaddons/ClickableAdvancements/files/9625404/debug.log)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

[latest.log](https://github.com/someaddons/ClickableAdvancements/files/9625411/latest.log)

**Comment by someaddons** [comment]
its a feature, which displays advancements in chat which normally are not shown. If you don't want those turn off the config on serverside
```
#By default vanilla only displays advancements in chat which get broadcasted to all online players,this setting turns on showing all advancements achieved in chat instead. 
That way you can findthe advancements you got easier/see better which you get. 
Some of these may have no actual text though because the advancement itself doesnt have any, e.g. Categories are advancements too. default = true
showAllInLocalChat = true
```
