### ISSUE TITLE
[Bug]: Game crashed when I clicked on an advancement in 1.18.2

### ISSUE THREAD

**Issue by DarkXFast** [someaddons/ClickableAdvancements#17]
### Describe the bug you're experiencing

Game crashed when I clicked on an advancement in 1.18.2.

### Reproducability

I clicked on an advancement and it crashed. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://crashy.net/6YnhjM4rwBQMK2YMTiqQ

**Comment by someaddons** [comment]
same crash as https://github.com/someaddons/ClickableAdvancements/issues/8 better advancements need to fix this
