### ISSUE TITLE
[Bug]: Incendium and Nullscape advancement links not working

### ISSUE THREAD

**Issue by MScott7** [someaddons/ClickableAdvancements#20]
### Describe the bug you're experiencing

The clickable links that appear in chat when unlocking an advancement from Incendium or Nullscape leads to "There doesn't seem to be anything here... :(", but when you look for the advancement yourself it's there. I would expect the link to bring up the proper advancement window instead of the black screen.

I apologize in advance if this is something you can't do anything about, but I think this is slightly different to the known issue where the link doesn't work when the advancement is not properly created/viewable. I do notice that these questionable advancements don't print the "[player] has made the advancement [X]" message in chat, just the link alone.

Screenshots showing two examples, one from each mod:
https://imgur.com/a/mnkW48d

Tested and present on 1.19.4 as well. Thanks for reading

### Reproducability

Install the latest 1.18.2 Fabric versions of Incendium and Nullscape (and dependency mods)
Travel to the Nether and End to trigger an Advancement from either mod
The link in chat will not bring you to the earned advancement, but it is present in the advancement menu

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Fabric

### Logs

https://gist.github.com/MScott7/744cda914d18b6d9d9caf179ef1a50c2

**Comment by someaddons** [comment]
works fine for me, I guess its the pageination advancement mods errors I see in the log causing issues
