### ISSUE TITLE
[Bug]: Tagged forge for fabric version

### ISSUE THREAD

**Issue by zachsai** [someaddons/ClickableAdvancements#21]
### Describe the bug you're experiencing

Hi,
You posted a new update for a fabric version but tagged it as forge, please fix so to not cause issues when updating in launcher for forge launcher.
https://www.curseforge.com/minecraft/mc-mods/clickable-advancements/files/4663534

1.20.1

### Reproducability

Hi,
You posted a new update for a fabric version but tagged it as forge, please fix so to not cause issues when updating in launcher for forge launcher.
https://www.curseforge.com/minecraft/mc-mods/clickable-advancements/files/4663534

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

none

**Comment by someaddons** [comment]
should be fixed, thanks for letting me know^^
