### ISSUE TITLE
[Bug]: Server & Client crashes (ATM9), NPE (1.20.1 3.7)

### ISSUE THREAD

**Issue by Burchard36** [someaddons/ClickableAdvancements#22]
### Describe the bug you're experiencing

Honestly, this crash is ENTIRELY random, and doesn't matter what advancement it is, we just keep getting this random NPE error that crashes only one of our servers & it keeps pointing to advancements being the issue, with one mod pointing directly at the Clickable Advancements mod

Here is some logs:

https://mclo.gs/WdY6zG4 (This is where i found this mod to be the main culprit)
https://mclo.gs/8mSi6qI (Random crash, no idea what from, but keeps mentioning advancements)
https://mclo.gs/XqVG5JL (Originally we thought it was sophisticated storage, but the error kept happening with other mods)

Seemingly every error is related to advancements, and one error calls this mod out in particular. I could be in the wrong here & this id a big modpack so it 100% could be an incompatibility with some mod, but I thought I would open this issue report here & just see if maybe, possibly somehow this mod is responsible 

### Reproducability

Absolutely none unfortunately, its driving me & my players mad attempting to figure out the root cause, this error can also happen with the client only crashing, and sometimes the server entirely crashing

~~Also I added the version to the title as the selectable options below are invalid~~ Fixed after opening this issue

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://mclo.gs/WdY6zG4 https://mclo.gs/8mSi6qI & https://mclo.gs/XqVG5JL

**Comment by someaddons** [comment]
some mod, can't tell which is either triggering advancements on a fakeplayer, or causing the players connection to get removed

**Comment by someaddons** [comment]
seems to be caused by: https://github.com/Aizistral-Studios/No-Chat-Reports/issues/460#issue-2078133802

**Comment by someaddons** [comment]
I added a crash prevention from my side and logging to call out the actual offending mod
