### ISSUE TITLE
Some mods / advancements aren't re-directing to their proper page (just a blank "There's nothing here")

### ISSUE THREAD

**Issue by manonillusts** [someaddons/ClickableAdvancements#3]
**Describe the bug**
Ok. I knew I wasn't crazy. I play-tested a blank world again to get a whole bunch of achievements. Some worked, so the mod definitely works. In fact quite a number worked. But quite a number also didn't work, and would re-direct to a black page with white text saying that there wasn't anything there. Basically it couldn't find the proper page.

**To Reproduce**
Better Minecraft/Plus modpack or Medieval Minecraft modpack, those are the ones I have shared mods that don't link properly.

**Expected behavior**
That it'd take me to the advancement.

** Mod version **
clickadv-1.8.jar

https://i.gyazo.com/1c266191e07b81745f07f486791ed30a.png
https://i.gyazo.com/c4c5f5bc8be0476edd7b90d7c3e99ac4.png
https://i.gyazo.com/4fd9569a200658bc9b56510dcda553fe.png
https://i.gyazo.com/d22c2dd2cbc3df951387843992b0a4b2.png
https://i.gyazo.com/ea5269f4079c40120ef94c69645c0d98.png
(some examples. The last one is from Dungeon Now Loading)

**Comment by someaddons** [comment]
checked into it and is indeed correct, those which do not display do not exist in the advancement screen at all. Seems to be mccreator mods and datapacks which do not properly add their advancements, so nothing I can do on my side
