### ISSUE TITLE
[Bug]: Crash in AOF5

### ISSUE THREAD

**Issue by agnor99** [someaddons/ClickableAdvancements#7]
### Describe the bug you're experiencing

I've clicked on an advancement and it crashed my game
[crash-2022-03-03_19.10.07-client.txt](https://github.com/someaddons/ClickableAdvancements/files/8180128/crash-2022-03-03_19.10.07-client.txt)

### Reproducability

Clicking on the advancement "You shall not... PASS!" causes the crash.
As the person obtaining the advancement previously found a village, so I assume the advancement is somewhat related to that.
As I'm a Forge only Dev I don't have my debugging utilities here, otherwise I would have given you the exact advancement id. Sorry for that

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://gist.github.com/agnor99/639ae888374f83ffde9a31465f1de090

**Comment by someaddons** [comment]
seems the advancement itself is bugged, w/e advancement that is. Its crashing because the advancement manager doesnt find the advancement for the ID. Gonna prevent crashing and log the missing ID instead.
