### ISSUE TITLE
[Bug]: Crash on clicking advancement if Better Advancements is installed

### ISSUE THREAD

**Issue by James103** [someaddons/ClickableAdvancements#8]
### Describe the bug you're experiencing

When clicking on an advancement, if Better Advancements is installed and the advancement has multiple criteria, the game crash shortly after with the following error:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.advancements.CriterionProgress.m_12911_()" because the return value of "net.minecraft.advancements.AdvancementProgress.m_8214_(String)" is null
```

Expected: The game should not crash and the advancement should flash properly.

### Reproducability

1. Earn/give an advancement with multiple criteria. Example: `advancement grant @s only adventure/kill_all_mobs`
2. Click on the name of the advancement in chat.

See also https://github.com/way2muchnoise/BetterAdvancements/issues/106

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/James103/c71541cb7945e2d744e7ff781dac3a32

**Comment by RedBeast1959** [comment]
Same problem happens in 1.19.2 Forge version.
It crashes when I click Hot tourist destination achievement.

[crash.txt](https://github.com/someaddons/ClickableAdvancements/files/9286809/crash.txt)

1.19.2 forge 43.0.2
clickadv-1.19.1-2.8.jar
BetterAdvancements-1.19.2-0.2.2.139.jar

**Comment by MoonMoonShark** [comment]
i know you already know about it, and i'm not trying to pile on, but my community is also having this problem in our modpack. player client crashes when they click on an advancement in chat.

Forge: 40.1.80
Minecraft: 1.18.2
Clickable Advancements: clickadv-1.18.2-2.5.jar
Better Advancements: BetterAdvancements-1.18.2-0.1.2.125.jar

**Comment by MokahTGS** [comment]
I'm not sure if you need more crash logs: https://pastebin.com/dznWCfkF

This is in the Cosmic Magitech modpack.

**Comment by someaddons** [comment]
should be fixed now by updating better advancements
