### ISSUE TITLE
[Bug]: [1.18.2] Client crash NPE when clicking on an advancement in chat, java.lang.NullPointerException: Cannot invoke "net.minecraft.advancements.Advancement.m_138319_()" because "current" is null

### ISSUE THREAD

**Issue by ProsperCraft** [someaddons/ClickableAdvancements#9]
### Describe the bug you're experiencing

Note that Better advancements is not installed.
clickadv-1.18.2-2.5

### Reproducability

Sit around afk all day, come back and accidently click on someone's advancement.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/ProsperCraft/e14b042b2187cb6b6c6a00927c931ffe

**Comment by someaddons** [comment]
fixed, some weird/bad advancement
